-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 15:51:06 2017
-- Model: facilsof_inventario    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facilsof_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facilsof_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facilsof_inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `facilsof_inventario` ;

-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_producto` (
  `inv_prod_id` INT NOT NULL AUTO_INCREMENT,
  `inv_prod_nombre` VARCHAR(200) NULL,
  `inv_prod_descripcion` TEXT NULL,
  `inv_prod_unidad` VARCHAR(50) NULL,
  `inv_prod_base_unidad` FLOAT NULL,
  PRIMARY KEY (`inv_prod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_unidad` (
  `ind_unid_id` INT NOT NULL AUTO_INCREMENT,
  `ind_unid_sku` INT NULL,
  `inv_unid_estado` VARCHAR(200) NULL,
  `inv_prod_id` INT NOT NULL,
  PRIMARY KEY (`ind_unid_id`),
  INDEX `fk_inv_unidad_inv_producto1_idx` (`inv_prod_id` ASC),
  CONSTRAINT `fk_inv_unidad_inv_producto1`
    FOREIGN KEY (`inv_prod_id`)
    REFERENCES `facilsof_inventario`.`inv_producto` (`inv_prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_atributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_atributo` (
  `inv_atr_id` INT NOT NULL AUTO_INCREMENT,
  `inv_atr_nombre` VARCHAR(200) NULL,
  `inv_atr_descripcion` TEXT NULL,
  `inv_prod_id` INT NOT NULL,
  PRIMARY KEY (`inv_atr_id`),
  INDEX `fk_inv_atributo_inv_producto_idx` (`inv_prod_id` ASC),
  CONSTRAINT `fk_inv_atributo_inv_producto`
    FOREIGN KEY (`inv_prod_id`)
    REFERENCES `facilsof_inventario`.`inv_producto` (`inv_prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_und_atr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_und_atr` (
  `inv_und_atr_id` INT NOT NULL AUTO_INCREMENT,
  `inv_und_atr_valor` VARCHAR(200) NULL,
  `inv_atr_id` INT NOT NULL,
  `ind_unid_id` INT NOT NULL,
  PRIMARY KEY (`inv_und_atr_id`),
  INDEX `fk_inv_und_atr_inv_atributo1_idx` (`inv_atr_id` ASC),
  INDEX `fk_inv_und_atr_inv_unidad1_idx` (`ind_unid_id` ASC),
  CONSTRAINT `fk_inv_und_atr_inv_atributo1`
    FOREIGN KEY (`inv_atr_id`)
    REFERENCES `facilsof_inventario`.`inv_atributo` (`inv_atr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_und_atr_inv_unidad1`
    FOREIGN KEY (`ind_unid_id`)
    REFERENCES `facilsof_inventario`.`inv_unidad` (`ind_unid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_usuario` (
  `inv_user_id` INT NOT NULL AUTO_INCREMENT,
  `inv_username` VARCHAR(100) NULL,
  `inv_password` VARCHAR(50) NULL,
  `inv_mail` VARCHAR(200) NULL,
  `inv_fono` INT NULL,
  PRIMARY KEY (`inv_user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
