-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 15:11:17 2017
-- Model: facilsof_inventario    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facilsof_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facilsof_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facilsof_inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `facilsof_inventario` ;

-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_producto` (
  `inv_prod_id` INT NOT NULL AUTO_INCREMENT,
  `inv_prod_nombre` VARCHAR(200) NULL,
  `inv_prod_descripcion` TEXT NULL,
  `inv_prod_unidad` VARCHAR(50) NULL,
  `inv_prod_base_unidad` FLOAT NULL,
  `inv_prod_prec_vta` INT NULL,
  `inv_prod_prec_cmp` INT NULL,
  PRIMARY KEY (`inv_prod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_est_und`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_est_und` (
  `inv_estund_id` INT NOT NULL AUTO_INCREMENT,
  `inv_estund_nombre` VARCHAR(100) NULL,
  `inv_estund_descripcion` TEXT NULL,
  PRIMARY KEY (`inv_estund_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_proveedor` (
  `inv_prov_id` INT NOT NULL AUTO_INCREMENT,
  `inv_prov_rut` VARCHAR(15) NULL,
  `inv_prov_nombre` VARCHAR(200) NULL,
  `inv_prov_direccion` VARCHAR(200) NULL,
  `inv_prov_ciudad` VARCHAR(100) NULL,
  `inv_prov_fono` INT NULL,
  `inv_prov_mail` VARCHAR(100) NULL,
  PRIMARY KEY (`inv_prov_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_compra` (
  `inv_cmp_id` INT NOT NULL AUTO_INCREMENT,
  `inv_cmp_fecha` VARCHAR(45) NULL,
  `inv_cmp_total` INT NULL,
  `inv_cmp_desc` INT NULL,
  `inv_prov_id` INT NULL,
  PRIMARY KEY (`inv_cmp_id`),
  INDEX `fk_inv_compra_inv_proveedor1_idx` (`inv_prov_id` ASC),
  CONSTRAINT `fk_inv_compra_inv_proveedor1`
    FOREIGN KEY (`inv_prov_id`)
    REFERENCES `facilsof_inventario`.`inv_proveedor` (`inv_prov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_cliente` (
  `inv_cln_id` INT NOT NULL AUTO_INCREMENT,
  `inv_cln_rut` VARCHAR(15) NULL,
  `inv_cln_nombre` VARCHAR(200) NULL,
  `inv_cln_direccion` VARCHAR(200) NULL,
  `inv_cln_ciudad` VARCHAR(100) NULL,
  `inv_cln_fono` INT NULL,
  `inv_cln_mail` VARCHAR(200) NULL,
  PRIMARY KEY (`inv_cln_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_venta` (
  `inv_vta_id` INT NOT NULL AUTO_INCREMENT,
  `inv_vta_fecha` VARCHAR(45) NULL,
  `inv_vta_total` INT NULL,
  `inv_vta_desc` INT NULL,
  `inv_cln_id` INT NULL,
  PRIMARY KEY (`inv_vta_id`),
  INDEX `fk_inv_venta_inv_cliente1_idx` (`inv_cln_id` ASC),
  CONSTRAINT `fk_inv_venta_inv_cliente1`
    FOREIGN KEY (`inv_cln_id`)
    REFERENCES `facilsof_inventario`.`inv_cliente` (`inv_cln_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_unidad` (
  `inv_unid_id` INT NOT NULL AUTO_INCREMENT,
  `inv_unid_sku` INT NULL,
  `inv_prod_id` INT NOT NULL,
  `inv_precio_costo` INT NULL,
  `inv_precio_vta` INT NULL,
  `inv_costo_neto` INT NULL,
  `inv_vta_neto` INT NULL,
  `inv_estund_id` INT NOT NULL,
  `inv_cmp_id` INT NULL,
  `inv_vta_id` INT NULL,
  PRIMARY KEY (`inv_unid_id`),
  INDEX `fk_inv_unidad_inv_producto1_idx` (`inv_prod_id` ASC),
  INDEX `fk_inv_unidad_inv_est_und1_idx` (`inv_estund_id` ASC),
  INDEX `fk_inv_unidad_inv_compra1_idx` (`inv_cmp_id` ASC),
  INDEX `fk_inv_unidad_inv_venta1_idx` (`inv_vta_id` ASC),
  CONSTRAINT `fk_inv_unidad_inv_producto1`
    FOREIGN KEY (`inv_prod_id`)
    REFERENCES `facilsof_inventario`.`inv_producto` (`inv_prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_unidad_inv_est_und1`
    FOREIGN KEY (`inv_estund_id`)
    REFERENCES `facilsof_inventario`.`inv_est_und` (`inv_estund_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_unidad_inv_compra1`
    FOREIGN KEY (`inv_cmp_id`)
    REFERENCES `facilsof_inventario`.`inv_compra` (`inv_cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_unidad_inv_venta1`
    FOREIGN KEY (`inv_vta_id`)
    REFERENCES `facilsof_inventario`.`inv_venta` (`inv_vta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_atributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_atributo` (
  `inv_atr_id` INT NOT NULL AUTO_INCREMENT,
  `inv_atr_nombre` VARCHAR(200) NULL,
  `inv_atr_descripcion` TEXT NULL,
  `inv_prod_id` INT NOT NULL,
  PRIMARY KEY (`inv_atr_id`),
  INDEX `fk_inv_atributo_inv_producto_idx` (`inv_prod_id` ASC),
  CONSTRAINT `fk_inv_atributo_inv_producto`
    FOREIGN KEY (`inv_prod_id`)
    REFERENCES `facilsof_inventario`.`inv_producto` (`inv_prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_und_atr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_und_atr` (
  `inv_und_atr_id` INT NOT NULL AUTO_INCREMENT,
  `inv_und_atr_valor` VARCHAR(200) NULL,
  `inv_atr_id` INT NOT NULL,
  `inv_unid_id` INT NOT NULL,
  PRIMARY KEY (`inv_und_atr_id`),
  INDEX `fk_inv_und_atr_inv_atributo1_idx` (`inv_atr_id` ASC),
  INDEX `fk_inv_und_atr_inv_unidad1_idx` (`inv_unid_id` ASC),
  CONSTRAINT `fk_inv_und_atr_inv_atributo1`
    FOREIGN KEY (`inv_atr_id`)
    REFERENCES `facilsof_inventario`.`inv_atributo` (`inv_atr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_und_atr_inv_unidad1`
    FOREIGN KEY (`inv_unid_id`)
    REFERENCES `facilsof_inventario`.`inv_unidad` (`inv_unid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facilsof_inventario`.`inv_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facilsof_inventario`.`inv_usuario` (
  `inv_user_id` INT NOT NULL AUTO_INCREMENT,
  `inv_username` VARCHAR(100) NULL,
  `inv_password` VARCHAR(50) NULL,
  `inv_mail` VARCHAR(200) NULL,
  `inv_fono` INT NULL,
  PRIMARY KEY (`inv_user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
